
#Image("images/char/kothorix/sideface/happy_face-arms.webp", xalign=0.01, yalign=1.0)

image side remy angry = Image("sdf/remy_angry.webp", xalign=0.01, yalign=1.0)
image side remy angry flip = Image("sdf/remy_angry.webp", xalign=0.01, yalign=1.0)
image side remy look = Image("sdf/remy_look.webp", xalign=0.01, yalign=1.0)
image side remy look flip = Image("sdf/remy_look.webp", xalign=0.01, yalign=1.0)
image side remy normal = Image("sdf/remy_normal.webp", xalign=0.01, yalign=1.0)
image side remy normal flip = Image("sdf/remy_normal.webp", xalign=0.01, yalign=1.0)
image side remy sad = Image("sdf/remy_sad.webp", xalign=0.01, yalign=1.0)
image side remy sad flip = Image("sdf/remy_sad.webp", xalign=0.01, yalign=1.0)
image side remy shy = Image("sdf/remy_shy.webp", xalign=0.01, yalign=1.0)
image side remy shy flip = Image("sdf/remy_shy.webp", xalign=0.01, yalign=1.0)
image side remy smile = Image("sdf/remy_smile.webp", xalign=0.01, yalign=1.0)
image side remy smile flip = Image("sdf/remy_smile.webp", xalign=0.01, yalign=1.0)


image side remy angry dk = Image(im.Recolor("sdf/remy_angry.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side remy look dk = Image(im.Recolor("sdf/remy_look.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side remy normal dk = Image(im.Recolor("sdf/remy_normal.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side remy sad dk = Image(im.Recolor("sdf/remy_sad.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side remy shy dk = Image(im.Recolor("sdf/remy_shy.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side remy smile dk = Image(im.Recolor("sdf/remy_smile.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)


image side remy angry c = Image("sdf/remy_angry_c.webp", xalign=0.01, yalign=1.0)
image side remy angry c flip = Image("sdf/remy_angry_c.webp", xalign=0.01, yalign=1.0)
image side remy look c = Image("sdf/remy_look_c.webp", xalign=0.01, yalign=1.0)
image side remy look c flip = Image("sdf/remy_look_c.webp", xalign=0.01, yalign=1.0)
image side remy normal c = Image("sdf/remy_normal_c.webp", xalign=0.01, yalign=1.0)
image side remy normal c flip = Image("sdf/remy_normal_c.webp", xalign=0.01, yalign=1.0)
image side remy sad c = Image("sdf/remy_sad_c.webp", xalign=0.01, yalign=1.0)
image side remy sad c flip = Image("sdf/remy_sad_c.webp", xalign=0.01, yalign=1.0)
image side remy shy c = Image("sdf/remy_shy_c.webp", xalign=0.01, yalign=1.0)
image side remy shy c flip = Image("sdf/remy_shy_c.webp", xalign=0.01, yalign=1.0)
image side remy smile c = Image("sdf/remy_smile_c.webp", xalign=0.01, yalign=1.0)
image side remy smile c flip = Image("sdf/remy_smile_c.webp", xalign=0.01, yalign=1.0)
image side remy angry b = Image("sdf/remy_angry_b.webp", xalign=0.01, yalign=1.0)
image side remy angry b flip = Image("sdf/remy_angry_b.webp", xalign=0.01, yalign=1.0)
image side remy look b = Image("sdf/remy_look_b.webp", xalign=0.01, yalign=1.0)
image side remy look b flip = Image("sdf/remy_look_b.webp", xalign=0.01, yalign=1.0)
image side remy normal b = Image("sdf/remy_normal_b.webp", xalign=0.01, yalign=1.0)
image side remy normal b flip = Image("sdf/remy_normal_b.webp", xalign=0.01, yalign=1.0)
image side remy sad b = Image("sdf/remy_sad_b.webp", xalign=0.01, yalign=1.0)
image side remy sad b flip = Image("sdf/remy_sad_b.webp", xalign=0.01, yalign=1.0)
image side remy shy b = Image("sdf/remy_shy_b.webp", xalign=0.01, yalign=1.0)
image side remy shy b flip = Image("sdf/remy_shy_b.webp", xalign=0.01, yalign=1.0)
image side remy smile b = Image("sdf/remy_smile_b.webp", xalign=0.01, yalign=1.0)
image side remy smile b flip = Image("sdf/remy_smile_b.webp", xalign=0.01, yalign=1.0)


image side emera normal = Image("sdf/emera_normal.webp", xalign=0.01, yalign=1.0)
image side emera normal flip = Image("sdf/emera_normal.webp", xalign=0.01, yalign=1.0)
image side emera normal b = Image("sdf/emera_normal_b.webp", xalign=0.01, yalign=1.0)
image side emera normal b flip = Image("sdf/emera_normal_b.webp", xalign=0.01, yalign=1.0)
image side emera frown = Image("sdf/emera_frown.webp", xalign=0.01, yalign=1.0)
image side emera frown flip = Image("sdf/emera_frown.webp", xalign=0.01, yalign=1.0)
image side emera frown b = Image("sdf/emera_frown_b.webp", xalign=0.01, yalign=1.0)
image side emera frown b flip = Image("sdf/emera_frown_b.webp", xalign=0.01, yalign=1.0)
image side emera laugh = Image("sdf/emera_laugh.webp", xalign=0.01, yalign=1.0)
image side emera laugh flip = Image("sdf/emera_laugh.webp", xalign=0.01, yalign=1.0)
image side emera laugh b = Image("sdf/emera_laugh_b.webp", xalign=0.01, yalign=1.0)
image side emera laugh b flip = Image("sdf/emera_laugh_b.webp", xalign=0.01, yalign=1.0)
image side emera mean = Image("sdf/emera_mean.webp", xalign=0.01, yalign=1.0)
image side emera mean flip = Image("sdf/emera_mean.webp", xalign=0.01, yalign=1.0)
image side emera mean b = Image("sdf/emera_mean_b.webp", xalign=0.01, yalign=1.0)
image side emera mean b flip = Image("sdf/emera_mean_b.webp", xalign=0.01, yalign=1.0)
image side emera ques = Image("sdf/emera_ques.webp", xalign=0.01, yalign=1.0)
image side emera ques flip = Image("sdf/emera_ques.webp", xalign=0.01, yalign=1.0)
image side emera ques b = Image("sdf/emera_ques_b.webp", xalign=0.01, yalign=1.0)
image side emera ques b flip = Image("sdf/emera_ques_b.webp", xalign=0.01, yalign=1.0)

image side damion normal = Image("sdf/damion_normal.webp", xalign=0.01, yalign=1.0)
image side damion face = Image("sdf/damion_face.webp", xalign=0.01, yalign=1.0)
image side damion arrogant = Image("sdf/damion_arrogant.webp", xalign=0.01, yalign=1.0)

image side sebastian normal = Image("sdf/sebastian_normal.webp", xalign=0.01, yalign=1.0)
image side sebastian normal b = Image("sdf/sebastian_normal_b.webp", xalign=0.01, yalign=1.0)
image side sebastian normal flip = Image("sdf/sebastian_normal.webp", xalign=0.01, yalign=1.0)
image side sebastian normal b flip = Image("sdf/sebastian_normal_b.webp", xalign=0.01, yalign=1.0)
image side sebastian normal flip dk = Image(im.Recolor("sdf/sebastian_normal.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side sebastian normal b flip dk = Image(im.Recolor("sdf/sebastian_normal_b.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side sebastian shy = Image("sdf/sebastian_shy.webp", xalign=0.01, yalign=1.0)
image side sebastian shy flip = Image("sdf/sebastian_shy.webp", xalign=0.01, yalign=1.0)
image side sebastian shy b = Image("sdf/sebastian_shy_b.webp", xalign=0.01, yalign=1.0)
image side sebastian shy b flip = Image("sdf/sebastian_shy_b.webp", xalign=0.01, yalign=1.0)
image side sebastian disapproval flip = Image("sdf/sebastian_disapproval.webp", xalign=0.01, yalign=1.0)
image side sebastian disapproval b flip = Image("sdf/sebastian_disapproval_b.webp", xalign=0.01, yalign=1.0)
image side sebastian disapproval = Image("sdf/sebastian_disapproval.webp", xalign=0.01, yalign=1.0)
image side sebastian disapproval b = Image("sdf/sebastian_disapproval_b.webp", xalign=0.01, yalign=1.0)
image side sebastian drop = Image("sdf/sebastian_drop.webp", xalign=0.01, yalign=1.0)
image side sebastian drop b = Image("sdf/sebastian_drop_b.webp", xalign=0.01, yalign=1.0)
image side sebastian drop flip = Image("sdf/sebastian_drop.webp", xalign=0.01, yalign=1.0)
image side sebastian drop b flip = Image("sdf/sebastian_drop_b.webp", xalign=0.01, yalign=1.0)
image side sebastian smile = Image("sdf/sebastian_smile.webp", xalign=0.01, yalign=1.0)
image side sebastian smile flip = Image("sdf/sebastian_smile.webp", xalign=0.01, yalign=1.0)
image side sebastian smile b = Image("sdf/sebastian_smile_b.webp", xalign=0.01, yalign=1.0)
image side sebastian smile b flip = Image("sdf/sebastian_smile_b.webp", xalign=0.01, yalign=1.0)
image side sebastian arm = Image("sdf/sebastian_arm.webp", xalign=0.01, yalign=1.0)
image side sebastian hand = Image("sdf/sebastian_arm.webp", xalign=0.01, yalign=1.0)

image side reza normal = Image("sdf/reza_normal.webp", xalign=0.01, yalign=1.0)
image side reza normalx = Image("sdf/reza_normalx.webp", xalign=0.01, yalign=1.0)
image side reza normal2 = Image("sdf/reza_normal2.webp", xalign=0.01, yalign=1.0)
image side reza normal dk = Image(im.Recolor("sdf/reza_normal.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side reza normal flip = Image("sdf/reza_normal.webp", xalign=0.01, yalign=1.0)
image side reza normal flip dk = Image(im.Recolor("sdf/reza_normal.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side reza amused = Image("sdf/reza_amused.webp", xalign=0.01, yalign=1.0)
image side reza amused flip = Image("sdf/reza_amused.webp", xalign=0.01, yalign=1.0)
image side reza annoyed = Image("sdf/reza_annoyed.webp", xalign=0.01, yalign=1.0)
image side reza annoyed flip = Image("sdf/reza_annoyed.webp", xalign=0.01, yalign=1.0)
image side reza angry = Image("sdf/reza_angry.webp", xalign=0.01, yalign=1.0)
image side reza angry flip = Image("sdf/reza_angry.webp", xalign=0.01, yalign=1.0)
image side reza angry flip dk = Image(im.Recolor("sdf/reza_angry.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side reza angry dk = Image(im.Recolor("sdf/reza_angry.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side reza gunpoint = Image("sdf/reza_gunpoint.webp", xalign=0.01, yalign=1.0)
image side reza gunpoint dk = Image(im.Recolor("sdf/reza_gunpoint.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side reza gunpoint flip = Image("sdf/reza_gunpoint.webp", xalign=0.01, yalign=1.0)
image side reza gunself = Image("sdf/reza_gunself.webp", xalign=0.01, yalign=1.0)
image side reza gunself flip = Image("sdf/reza_gunself.webp", xalign=0.01, yalign=1.0)
image side reza laugh = Image("sdf/reza_laugh.webp", xalign=0.01, yalign=1.0)
image side reza laugh flip = Image("sdf/reza_laugh.webp", xalign=0.01, yalign=1.0)
image side reza rage = Image("sdf/reza_rage.webp", xalign=0.01, yalign=1.0)
image side reza rage flip = Image("sdf/reza_rage.webp", xalign=0.01, yalign=1.0)
image side reza defeat = Image("sdf/reza_defeat.webp", xalign=0.01, yalign=1.0)
image side reza defeat flip = Image("sdf/reza_defeat.webp", xalign=0.01, yalign=1.0)

image side reza annoyed b = Image("sdf/reza_annoyed_b.webp", xalign=0.01, yalign=1.0)
image side reza annoyed b flip = Image("sdf/reza_annoyed_b.webp", xalign=0.01, yalign=1.0)
image side reza gunself b = Image("sdf/reza_gunself_b.webp", xalign=0.01, yalign=1.0)
image side reza gunself b flip = Image("sdf/reza_gunself_b.webp", xalign=0.01, yalign=1.0)
image side reza angry b = Image("sdf/reza_angry_b.webp", xalign=0.01, yalign=1.0)
image side reza angry b flip = Image("sdf/reza_angry_b.webp", xalign=0.01, yalign=1.0)
image side reza gunpoint b = Image("sdf/reza_gunpoint_b.webp", xalign=0.01, yalign=1.0)
image side reza gunpoint b flip = Image("sdf/reza_gunpoint_b.webp", xalign=0.01, yalign=1.0)

image side maverick normal = Image("sdf/maverick_normal.webp", xalign=0.01, yalign=1.0)
image side maverick normal dk = Image(im.Recolor("sdf/maverick_normal.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side maverick angry = Image("sdf/maverick_angry.webp", xalign=0.01, yalign=1.0)
image side maverick angry dk = Image(im.Recolor("sdf/maverick_angry.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side maverick normal flip = Image("sdf/maverick_normal.webp", xalign=0.01, yalign=1.0)
image side maverick normal flip dk = Image(im.Recolor("sdf/maverick_normal.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side maverick angry flip = Image("sdf/maverick_angry.webp", xalign=0.01, yalign=1.0)
image side maverick angry flip dk = Image(im.Recolor("sdf/maverick_angry.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side maverick nice = Image("sdf/maverick_nice.webp", xalign=0.01, yalign=1.0)
image side maverick nice c = Image("sdf/maverick_nice_c.webp", xalign=0.01, yalign=1.0)
image side maverick nice flip = Image("sdf/maverick_nice.webp", xalign=0.01, yalign=1.0)
image side maverick nice c flip = Image("sdf/maverick_nice_c.webp", xalign=0.01, yalign=1.0)
image side maverick scared = Image("sdf/maverick_scared.webp", xalign=0.01, yalign=1.0)
image side maverick normal b = Image("sdf/maverick_normal_b.webp", xalign=0.01, yalign=1.0)
image side maverick angry b = Image("sdf/maverick_angry_b.webp", xalign=0.01, yalign=1.0)
image side maverick nice b = Image("sdf/maverick_nice_b.webp", xalign=0.01, yalign=1.0)
image side maverick scared b = Image("sdf/maverick_scared_b.webp", xalign=0.01, yalign=1.0)
image side maverick nice b gray = Image(im.Grayscale("sdf/maverick_nice_b.webp"), xalign=0.01, yalign=1.0)
image side maverick nice b sepia = Image(im.Sepia("sdf/maverick_nice_b.webp"), xalign=0.01, yalign=1.0)
image side maverick scared b gray = Image(im.Grayscale("sdf/maverick_scared_b.webp"), xalign=0.01, yalign=1.0)
image side maverick laugh = Image("sdf/maverick_laugh.webp", xalign=0.01, yalign=1.0)
image side maverick laugh flip = Image("sdf/maverick_laugh.webp", xalign=0.01, yalign=1.0)
image side maverick normal c = Image("sdf/maverick_normal_c.webp", xalign=0.01, yalign=1.0)
image side maverick normal c flip = Image("sdf/maverick_normal_c.webp", xalign=0.01, yalign=1.0)
image side maverick angry c = Image("sdf/maverick_angry_c.webp", xalign=0.01, yalign=1.0)
image side maverick angry c flip = Image("sdf/maverick_angry_c.webp", xalign=0.01, yalign=1.0)
image side maverick rage = Image("sdf/maverick_rage.webp", xalign=0.01, yalign=1.0)
image side maverick rage flip = Image("sdf/maverick_rage.webp", xalign=0.01, yalign=1.0)
image side maverick rage b = Image("sdf/maverick_rage_b.webp", xalign=0.01, yalign=1.0)
image side maverick rage b flip = Image("sdf/maverick_rage_b.webp", xalign=0.01, yalign=1.0)
image side maverick rage c = Image("sdf/maverick_rage_c.webp", xalign=0.01, yalign=1.0)
image side maverick rage c flip = Image("sdf/maverick_rage_c.webp", xalign=0.01, yalign=1.0)
image side maverick rage d = Image("sdf/maverick_rage_d.webp", xalign=0.01, yalign=1.0)
image side maverick rage d flip = Image("sdf/maverick_rage_d.webp", xalign=0.01, yalign=1.0)


image side vara normal = Image("sdf/vara_normal.webp", xalign=0.01, yalign=1.0)
image side vara normal flip = Image("sdf/vara_normal.webp", xalign=0.01, yalign=1.0)
image side vara none = Image("sdf/vara_none.webp", xalign=0.01, yalign=1.0)
image side vara none flip = Image("sdf/vara_none.webp", xalign=0.01, yalign=1.0)
image side vara sad = Image("sdf/vara_sad.webp", xalign=0.01, yalign=1.0)
image side vara sad flip = Image("sdf/vara_sad.webp", xalign=0.01, yalign=1.0)
image side vara growl = Image("sdf/vara_growl.webp", xalign=0.01, yalign=1.0)
image side vara growl flip = Image("sdf/vara_growl.webp", xalign=0.01, yalign=1.0)
image side vara shocked = Image("sdf/vara_shocked.webp", xalign=0.01, yalign=1.0)
image side vara shocked flip = Image("sdf/vara_shocked.webp", xalign=0.01, yalign=1.0)
image side vara shocked2 = Image("sdf/vara_shocked2.webp", xalign=0.01, yalign=1.0)
image side vara shocked2 flip = Image("sdf/vara_shocked2.webp", xalign=0.01, yalign=1.0)

image side amely normal = Image("sdf/amely_normal_flip.webp", xalign=0.01, yalign=1.0)
image side amely normal flip = Image("sdf/amely_normal_flip.webp", xalign=0.01, yalign=1.0)

image side anna normal = Image("sdf/anna_normal.webp", xalign=0.01, yalign=1.0)
image side anna normal b = Image("sdf/anna_normal_b.webp", xalign=0.01, yalign=1.0)
image side anna normal c = Image("sdf/anna_normal_c.webp", xalign=0.01, yalign=1.0)
image side anna normal flip = Image("sdf/anna_normal.webp", xalign=0.01, yalign=1.0)
image side anna normal b flip = Image("sdf/anna_normal_b.webp", xalign=0.01, yalign=1.0)
image side anna face = Image("sdf/anna_face.webp", xalign=0.01, yalign=1.0)
image side anna face flip = Image("sdf/anna_face.webp", xalign=0.01, yalign=1.0)
image side anna face b = Image("sdf/anna_face_b.webp", xalign=0.01, yalign=1.0)
image side anna face c = Image("sdf/anna_face_c.webp", xalign=0.01, yalign=1.0)
image side anna face b flip = Image("sdf/anna_face_b.webp", xalign=0.01, yalign=1.0)
image side anna smirk = Image("sdf/anna_smirk.webp", xalign=0.01, yalign=1.0)
image side anna smirk flip = Image("sdf/anna_smirk.webp", xalign=0.01, yalign=1.0)
image side anna smirk b = Image("sdf/anna_smirk_b.webp", xalign=0.01, yalign=1.0)
image side anna smirk c = Image("sdf/anna_smirk_c.webp", xalign=0.01, yalign=1.0)
image side anna smirk b flip = Image("sdf/anna_smirk_b.webp", xalign=0.01, yalign=1.0)
image side anna sad = Image("sdf/anna_sad.webp", xalign=0.01, yalign=1.0)
image side anna sad flip = Image("sdf/anna_sad.webp", xalign=0.01, yalign=1.0)
image side anna sad b = Image("sdf/anna_sad_b.webp", xalign=0.01, yalign=1.0)
image side anna sad c = Image("sdf/anna_sad_c.webp", xalign=0.01, yalign=1.0)
image side anna sad b flip = Image("sdf/anna_sad_b.webp", xalign=0.01, yalign=1.0)
image side anna disgust = Image("sdf/anna_disgust.webp", xalign=0.01, yalign=1.0)
image side anna disgust flip = Image("sdf/anna_disgust.webp", xalign=0.01, yalign=1.0)
image side anna disgust b = Image("sdf/anna_disgust_b.webp", xalign=0.01, yalign=1.0)
image side anna disgust c = Image("sdf/anna_disgust_c.webp", xalign=0.01, yalign=1.0)
image side anna disgust b flip = Image("sdf/anna_disgust_b.webp", xalign=0.01, yalign=1.0)
image side anna rage = Image("sdf/anna_rage.webp", xalign=0.01, yalign=1.0)
image side anna rage flip = Image("sdf/anna_rage.webp", xalign=0.01, yalign=1.0)
image side anna rage b = Image("sdf/anna_rage_b.webp", xalign=0.01, yalign=1.0)
image side anna rage c = Image("sdf/anna_rage_c.webp", xalign=0.01, yalign=1.0)
image side anna rage b flip = Image("sdf/anna_rage_b.webp", xalign=0.01, yalign=1.0)

image side anna cry = Image("sdf/anna_cry.webp", xalign=0.01, yalign=1.0)
image side anna cry flip = Image("sdf/anna_cry.webp", xalign=0.01, yalign=1.0)
image side anna cry b = Image("sdf/anna_cry_b.webp", xalign=0.01, yalign=1.0)
image side anna cry b flip = Image("sdf/anna_cry_b.webp", xalign=0.01, yalign=1.0)
image side anna cry e = Image("sdf/anna_cry_e.webp", xalign=0.01, yalign=1.0)
image side anna cry e flip = Image("sdf/anna_cry_e.webp", xalign=0.01, yalign=1.0)
image side anna cry f = Image("sdf/anna_cry_f.webp", xalign=0.01, yalign=1.0)
image side anna cry f flip = Image("sdf/anna_cry_f.webp", xalign=0.01, yalign=1.0)

image side anna despair = Image("sdf/anna_despair.webp", xalign=0.01, yalign=1.0)
image side anna despair flip = Image("sdf/anna_despair.webp", xalign=0.01, yalign=1.0)
image side anna despair b = Image("sdf/anna_despair_b.webp", xalign=0.01, yalign=1.0)
image side anna despair b flip = Image("sdf/anna_despair_b.webp", xalign=0.01, yalign=1.0)

image side adine normal = Image("sdf/adine_normal.webp", xalign=0.01, yalign=1.0)
image side adine normal b = Image("sdf/adine_normal_b.webp", xalign=0.01, yalign=1.0)
image side adine normal flip = Image("sdf/adine_normal.webp", xalign=0.01, yalign=1.0)
image side adine normal b flip = Image("sdf/adine_normal_b.webp", xalign=0.01, yalign=1.0)
image side adine giggle = Image("sdf/adine_giggle.webp", xalign=0.01, yalign=1.0)
image side adine giggle flip = Image("sdf/adine_giggle.webp", xalign=0.01, yalign=1.0)
image side adine giggle b flip = Image("sdf/adine_giggle_b.webp", xalign=0.01, yalign=1.0)
image side adine giggle b = Image("sdf/adine_giggle_b.webp", xalign=0.01, yalign=1.0)
image side adine disappoint = Image("sdf/adine_disappoint.webp", xalign=0.01, yalign=1.0)
image side adine disappoint b = Image("sdf/adine_disappoint_b.webp", xalign=0.01, yalign=1.0)
image side adine disappoint flip = Image("sdf/adine_disappoint.webp", xalign=0.01, yalign=1.0)
image side adine disappoint b flip = Image("sdf/adine_disappoint_b.webp", xalign=0.01, yalign=1.0)
image side adine annoyed = Image("sdf/adine_annoyed.webp", xalign=0.01, yalign=1.0)
image side adine annoyed flip = Image("sdf/adine_annoyed.webp", xalign=0.01, yalign=1.0)
image side adine annoyed b flip = Image("sdf/adine_annoyed_b.webp", xalign=0.01, yalign=1.0)
image side adine annoyed b = Image("sdf/adine_annoyed_b.webp", xalign=0.01, yalign=1.0)
image side adine sad = Image("sdf/adine_sad.webp", xalign=0.01, yalign=1.0)
image side adine sad flip = Image("sdf/adine_sad.webp", xalign=0.01, yalign=1.0)
image side adine sad b = Image("sdf/adine_sad_b.webp", xalign=0.01, yalign=1.0)
image side adine sad b flip = Image("sdf/adine_sad_b.webp", xalign=0.01, yalign=1.0)
image side adine think = Image("sdf/adine_think.webp", xalign=0.01, yalign=1.0)
image side adine think b = Image("sdf/adine_think_b.webp", xalign=0.01, yalign=1.0)
image side adine think flip = Image("sdf/adine_think.webp", xalign=0.01, yalign=1.0)
image side adine think b flip = Image("sdf/adine_think_b.webp", xalign=0.01, yalign=1.0)


image side adine normal c = Image("sdf/adine_normal_c.webp", xalign=0.01, yalign=1.0)
image side adine normal c flip = Image("sdf/adine_normal_c.webp", xalign=0.01, yalign=1.0)
image side adine giggle c flip = Image("sdf/adine_giggle_c.webp", xalign=0.01, yalign=1.0)
image side adine giggle c = Image("sdf/adine_giggle_c.webp", xalign=0.01, yalign=1.0)
image side adine disappoint c = Image("sdf/adine_disappoint_c.webp", xalign=0.01, yalign=1.0)
image side adine disappoint c flip = Image("sdf/adine_disappoint_c.webp", xalign=0.01, yalign=1.0)
image side adine annoyed c flip = Image("sdf/adine_annoyed_c.webp", xalign=0.01, yalign=1.0)
image side adine annoyed c = Image("sdf/adine_annoyed_c.webp", xalign=0.01, yalign=1.0)
image side adine sad c = Image("sdf/adine_sad_c.webp", xalign=0.01, yalign=1.0)
image side adine sad c flip = Image("sdf/adine_sad_c.webp", xalign=0.01, yalign=1.0)
image side adine think c = Image("sdf/adine_think_c.webp", xalign=0.01, yalign=1.0)
image side adine think c flip = Image("sdf/adine_think_c.webp", xalign=0.01, yalign=1.0)

image side adine frustrated = Image("sdf/adine_frustrated.webp", xalign=0.01, yalign=1.0)
image side adine frustrated b = Image("sdf/adine_frustrated_b.webp", xalign=0.01, yalign=1.0)
image side adine frustrated c = Image("sdf/adine_frustrated_c.webp", xalign=0.01, yalign=1.0)

image side adine frustrated flip = Image("sdf/adine_frustrated.webp", xalign=0.01, yalign=1.0)
image side adine frustrated b flip = Image("sdf/adine_frustrated_b.webp", xalign=0.01, yalign=1.0)
image side adine frustrated c flip = Image("sdf/adine_frustrated_c.webp", xalign=0.01, yalign=1.0)

image side adine sad d = Image("sdf/adine_sad_d.webp", xalign=0.01, yalign=1.0)
image side adine sad d flip = Image("sdf/adine_sad_d.webp", xalign=0.01, yalign=1.0)
image side adine sad e = Image("sdf/adine_sad_e.webp", xalign=0.01, yalign=1.0)
image side adine sad e flip = Image("sdf/adine_sad_e.webp", xalign=0.01, yalign=1.0)
image side adine sad f = Image("sdf/adine_sad_f.webp", xalign=0.01, yalign=1.0)
image side adine sad f flip = Image("sdf/adine_sad_f.webp", xalign=0.01, yalign=1.0)

image side izumi normal = Image("sdf/izumi_normal.webp", xalign=0.01, yalign=1.0)
image side izumi normal flip = Image("sdf/izumi_normal.webp", xalign=0.01, yalign=1.0)

image side izumi normal 1 = Image("sdf/izumi_normal_1.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 flip = Image("sdf/izumi_normal_1.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 gray = Image(im.Grayscale("sdf/izumi_normal_1.webp"), xalign=0.01, yalign=1.0)
image side izumi normal 2 = Image("sdf/izumi_normal_2.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 flip = Image("sdf/izumi_normal_2.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 = Image("sdf/izumi_normal_3.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 flip = Image("sdf/izumi_normal_3.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 = Image("sdf/izumi_normal_4.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 flip = Image("sdf/izumi_normal_4.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 = Image("sdf/izumi_normal_5.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 flip = Image("sdf/izumi_normal_5.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 = Image("sdf/izumi_normal_6.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 flip = Image("sdf/izumi_normal_6.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 = Image("sdf/izumi_normal_7.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 flip = Image("sdf/izumi_normal_7.webp", xalign=0.01, yalign=1.0)

image side izumi normal 1 scar = Image("sdf/izumi_normal_1_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 scar flip = Image("sdf/izumi_normal_1_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 scar = Image("sdf/izumi_normal_2_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 scar flip = Image("sdf/izumi_normal_2_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 scar = Image("sdf/izumi_normal_3_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 scar flip = Image("sdf/izumi_normal_3_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 scar = Image("sdf/izumi_normal_4_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 scar flip = Image("sdf/izumi_normal_4_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 scar = Image("sdf/izumi_normal_5_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 scar flip = Image("sdf/izumi_normal_5_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 scar = Image("sdf/izumi_normal_6_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 scar flip = Image("sdf/izumi_normal_6_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 scar = Image("sdf/izumi_normal_7_scar.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 scar flip = Image("sdf/izumi_normal_7_scar.webp", xalign=0.01, yalign=1.0)

image side izumi normal 1 b = Image("sdf/izumi_normal_1_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 b flip = Image("sdf/izumi_normal_1_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 b gray = Image(im.Grayscale("sdf/izumi_normal_1_b.webp"), xalign=0.01, yalign=1.0)
image side izumi normal 2 b = Image("sdf/izumi_normal_2_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 b flip = Image("sdf/izumi_normal_2_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 b = Image("sdf/izumi_normal_3_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 b flip = Image("sdf/izumi_normal_3_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 b = Image("sdf/izumi_normal_4_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 b flip = Image("sdf/izumi_normal_4_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 b = Image("sdf/izumi_normal_5_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 b flip = Image("sdf/izumi_normal_5_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 b = Image("sdf/izumi_normal_6_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 b flip = Image("sdf/izumi_normal_6_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 b = Image("sdf/izumi_normal_7_b.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 b flip = Image("sdf/izumi_normal_7_b.webp", xalign=0.01, yalign=1.0)

image side izumi normal 1 c = Image("sdf/izumi_normal_1_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 c flip = Image("sdf/izumi_normal_1_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 c = Image("sdf/izumi_normal_2_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 c flip = Image("sdf/izumi_normal_2_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 c = Image("sdf/izumi_normal_3_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 c flip = Image("sdf/izumi_normal_3_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 c = Image("sdf/izumi_normal_4_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 c flip = Image("sdf/izumi_normal_4_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 c = Image("sdf/izumi_normal_5_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 c flip = Image("sdf/izumi_normal_5_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 c = Image("sdf/izumi_normal_6_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 c flip = Image("sdf/izumi_normal_6_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 c = Image("sdf/izumi_normal_7_c.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 c flip = Image("sdf/izumi_normal_7_c.webp", xalign=0.01, yalign=1.0)

image side izumi normal 1 d = Image("sdf/izumi_normal_1_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 1 d flip = Image("sdf/izumi_normal_1_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 d = Image("sdf/izumi_normal_2_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 2 d flip = Image("sdf/izumi_normal_2_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 d = Image("sdf/izumi_normal_3_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 3 d flip = Image("sdf/izumi_normal_3_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 d = Image("sdf/izumi_normal_4_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 4 d flip = Image("sdf/izumi_normal_4_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 d = Image("sdf/izumi_normal_5_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 5 d flip = Image("sdf/izumi_normal_5_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 d = Image("sdf/izumi_normal_6_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 6 d flip = Image("sdf/izumi_normal_6_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 d = Image("sdf/izumi_normal_7_d.webp", xalign=0.01, yalign=1.0)
image side izumi normal 7 d flip = Image("sdf/izumi_normal_7_d.webp", xalign=0.01, yalign=1.0)

image side katsu normal = Image("sdf/katsu_normal.webp", xalign=0.01, yalign=1.0)
image side katsu exhausted = Image("sdf/katsu_exhausted.webp", xalign=0.01, yalign=1.0)
image side katsu excited = Image("sdf/katsu_excited.webp", xalign=0.01, yalign=1.0)
image side katsu smile = Image("sdf/katsu_smile.webp", xalign=0.01, yalign=1.0)

image side katsu normal flip = Image("sdf/katsu_normal.webp", xalign=0.01, yalign=1.0)
image side katsu exhausted flip = Image("sdf/katsu_exhausted.webp", xalign=0.01, yalign=1.0)
image side katsu excited flip = Image("sdf/katsu_excited.webp", xalign=0.01, yalign=1.0)
image side katsu smile flip = Image("sdf/katsu_smile.webp", xalign=0.01, yalign=1.0)

image side katsu normal dk = Image(im.Recolor("sdf/katsu_normal.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side katsu exhausted dk = Image(im.Recolor("sdf/katsu_exhausted.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side katsu excited dk = Image(im.Recolor("sdf/katsu_excited.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side katsu smile dk = Image(im.Recolor("sdf/katsu_smile.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)

image side katsu normal flip dk = Image(im.Recolor("sdf/katsu_normal.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side katsu exhausted flip dk = Image(im.Recolor("sdf/katsu_exhausted.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side katsu excited flip dk = Image(im.Recolor("sdf/katsu_excited.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)
image side katsu smile flip dk = Image(im.Recolor("sdf/katsu_smile.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0)

image side kevin normal = Image("sdf/kevin_normal.webp", xalign=0.01, yalign=1.0)
image side kevin ramble = Image("sdf/kevin_ramble.webp", xalign=0.01, yalign=1.0)
image side kevin face = Image("sdf/kevin_face.webp", xalign=0.01, yalign=1.0)
image side kevin brow = Image("sdf/kevin_brow.webp", xalign=0.01, yalign=1.0)

image side kevin normal flip = Image("sdf/kevin_normal.webp", xalign=0.01, yalign=1.0)
image side kevin ramble flip = Image("sdf/kevin_ramble.webp", xalign=0.01, yalign=1.0)
image side kevin face flip = Image("sdf/kevin_face.webp", xalign=0.01, yalign=1.0)
image side kevin brow flip = Image("sdf/kevin_brow.webp", xalign=0.01, yalign=1.0)

image side lorem normal = Image("sdf/lorem_normal.webp", xalign=0.01, yalign=1.0)
image side lorem normal flip = Image("sdf/lorem_normal.webp", xalign=0.01, yalign=1.0)
image side lorem normal b = Image("sdf/lorem_normal_b.webp", xalign=0.01, yalign=1.0)
image side lorem normal b flip = Image("sdf/lorem_normal_b.webp", xalign=0.01, yalign=1.0)

image side lorem happy = Image("sdf/lorem_happy.webp", xalign=0.01, yalign=1.0)
image side lorem happy flip = Image("sdf/lorem_happy.webp", xalign=0.01, yalign=1.0)
image side lorem happy b = Image("sdf/lorem_happy_b.webp", xalign=0.01, yalign=1.0)
image side lorem happy b flip = Image("sdf/lorem_happy_b.webp", xalign=0.01, yalign=1.0)

image side lorem relieved = Image("sdf/lorem_relieved.webp", xalign=0.01, yalign=1.0)
image side lorem relieved flip = Image("sdf/lorem_relieved.webp", xalign=0.01, yalign=1.0)
image side lorem relieved b = Image("sdf/lorem_relieved_b.webp", xalign=0.01, yalign=1.0)
image side lorem relieved b flip = Image("sdf/lorem_relieved_b.webp", xalign=0.01, yalign=1.0)

image side lorem sad = Image("sdf/lorem_sad.webp", xalign=0.01, yalign=1.0)
image side lorem sad flip = Image("sdf/lorem_sad.webp", xalign=0.01, yalign=1.0)
image side lorem sad b = Image("sdf/lorem_sad_b.webp", xalign=0.01, yalign=1.0)
image side lorem sad b flip = Image("sdf/lorem_sad_b.webp", xalign=0.01, yalign=1.0)

image side lorem shy = Image("sdf/lorem_shy.webp", xalign=0.01, yalign=1.0)
image side lorem shy flip = Image("sdf/lorem_shy.webp", xalign=0.01, yalign=1.0)
image side lorem shy b = Image("sdf/lorem_shy_b.webp", xalign=0.01, yalign=1.0)
image side lorem shy b flip = Image("sdf/lorem_shy_b.webp", xalign=0.01, yalign=1.0)

image side lorem think = Image("sdf/lorem_think.webp", xalign=0.01, yalign=1.0)
image side lorem think flip = Image("sdf/lorem_think.webp", xalign=0.01, yalign=1.0)
image side lorem think b = Image("sdf/lorem_think_b.webp", xalign=0.01, yalign=1.0)
image side lorem think b flip = Image("sdf/lorem_think_b.webp", xalign=0.01, yalign=1.0)

image side ipsum normal = Image("sdf/ipsum_normal.webp", xalign=0.01, yalign=1.0)
image side ipsum normal flip = Image("sdf/ipsum_normal.webp", xalign=0.01, yalign=1.0)

image side ipsum happy = Image("sdf/ipsum_happy.webp", xalign=0.01, yalign=1.0)
image side ipsum happy flip = Image("sdf/ipsum_happy.webp", xalign=0.01, yalign=1.0)

image side ipsum sad = Image("sdf/ipsum_sad.webp", xalign=0.01, yalign=1.0)
image side ipsum sad flip = Image("sdf/ipsum_sad.webp", xalign=0.01, yalign=1.0)

image side ipsum think = Image("sdf/ipsum_think.webp", xalign=0.01, yalign=1.0)
image side ipsum think flip = Image("sdf/ipsum_think.webp", xalign=0.01, yalign=1.0)

image side bryce stern b old gray = Image(im.Grayscale("sdf/bryce_stern_b_old_flip.webp"), xalign=0.01, yalign=1.0)
image side bryce brow b old gray = Image(im.Grayscale("sdf/bryce_brow_b_old_flip.webp"), xalign=0.01, yalign=1.0)

image side bryce normal = Image("sdf/bryce_normal_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal b = Image("sdf/bryce_normal_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal old = Image("sdf/bryce_normal_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal b old = Image("sdf/bryce_normal_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal flip = Image("sdf/bryce_normal_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal b flip = Image("sdf/bryce_normal_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal b old flip = Image("sdf/bryce_normal_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce brow = Image("sdf/bryce_brow_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow b = Image("sdf/bryce_brow_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow old = Image("sdf/bryce_brow_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow b old = Image("sdf/bryce_brow_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow flip = Image("sdf/bryce_brow_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow b flip = Image("sdf/bryce_brow_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow b old flip = Image("sdf/bryce_brow_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce flirty = Image("sdf/bryce_flirty_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty b = Image("sdf/bryce_flirty_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty flip = Image("sdf/bryce_flirty_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty b flip = Image("sdf/bryce_flirty_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty old = Image("sdf/bryce_flirty_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty b old = Image("sdf/bryce_flirty_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty b old flip = Image("sdf/bryce_flirty_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce laugh = Image("sdf/bryce_laugh_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh b = Image("sdf/bryce_laugh_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh flip = Image("sdf/bryce_laugh_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh b flip = Image("sdf/bryce_laugh_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh old = Image("sdf/bryce_laugh_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh b old = Image("sdf/bryce_laugh_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh b old flip = Image("sdf/bryce_laugh_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce smirk = Image("sdf/bryce_smirk_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk b = Image("sdf/bryce_smirk_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk flip = Image("sdf/bryce_smirk_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk b flip = Image("sdf/bryce_smirk_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk old = Image("sdf/bryce_smirk_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk b old = Image("sdf/bryce_smirk_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk b old flip = Image("sdf/bryce_smirk_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce stern = Image("sdf/bryce_stern_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern b = Image("sdf/bryce_stern_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern flip = Image("sdf/bryce_stern_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern b flip = Image("sdf/bryce_stern_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern old = Image("sdf/bryce_stern_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern b old = Image("sdf/bryce_stern_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern b old flip = Image("sdf/bryce_stern_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce angry = Image("sdf/bryce_angry_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry b = Image("sdf/bryce_angry_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry flip = Image("sdf/bryce_angry_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry b flip = Image("sdf/bryce_angry_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry old = Image("sdf/bryce_angry_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry b old = Image("sdf/bryce_angry_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry b old flip = Image("sdf/bryce_angry_b_old_flip.webp", xalign=0.01, yalign=1.0)

image side bryce normal dk = Image(im.Recolor("sdf/bryce_normal_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce normal b dk = Image(im.Recolor("sdf/bryce_normal_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce brow dk = Image(im.Recolor("sdf/bryce_brow_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce brow b dk = Image(im.Recolor("sdf/bryce_brow_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce flirty dk = Image(im.Recolor("sdf/bryce_flirty_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce flirty b dk = Image(im.Recolor("sdf/bryce_flirty_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce laugh dk = Image(im.Recolor("sdf/bryce_laugh_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce laugh b dk = Image(im.Recolor("sdf/bryce_laugh_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce smirk dk = Image(im.Recolor("sdf/bryce_smirk_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce smirk b dk = Image(im.Recolor("sdf/bryce_smirk_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce stern dk = Image(im.Recolor("sdf/bryce_stern_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce stern b dk = Image(im.Recolor("sdf/bryce_stern_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)

image side bryce sad = Image("sdf/bryce_sad_flip.webp", xalign=0.01, yalign=1.0)
image side bryce sad b = Image("sdf/bryce_sad_b_flip.webp", xalign=0.01, yalign=1.0)

#
image side 8th normal = Image("sdf/8th_normal.webp", xalign=0.01, yalign=1.0)
image side 8th normal flip = Image("sdf/8th_normal.webp", xalign=0.01, yalign=1.0)
#
image side dramavian normal = Image("sdf/dramavian_normal.webp", xalign=0.01, yalign=1.0)
image side dramavian normal flip = Image("sdf/dramavian_normal.webp", xalign=0.01, yalign=1.0)

image side xith normal = Image("sdf/xith_normal.webp", xalign=0.01, yalign=1.0)
image side xith normal flip = Image("sdf/xith_normal.webp", xalign=0.01, yalign=1.0)

image side lucius normal = Image("sdf/lucius_normal.webp", xalign=0.01, yalign=1.0)
image side lucius normal flip = Image("sdf/lucius_normal.webp", xalign=0.01, yalign=1.0)

image side ophinia normal = Image("sdf/ophinia_normal.webp", xalign=0.01, yalign=1.0)
image side ophinia normal flip = Image("sdf/ophinia_normal.webp", xalign=0.01, yalign=1.0)

image side kalinth normal = Image("sdf/kalinth_normal.webp", xalign=0.01, yalign=1.0)
image side kalinth normal flip = Image("sdf/kalinth_normal.webp", xalign=0.01, yalign=1.0)

image side grey normal = Image("sdf/grey_normal.webp", xalign=0.01, yalign=1.0)
image side grey normal flip = Image("sdf/grey_normal.webp", xalign=0.01, yalign=1.0)

image side leymas normal = Image("sdf/leymas_normal.webp", xalign=0.01, yalign=1.0)
image side leymas normal flip = Image("sdf/leymas_normal.webp", xalign=0.01, yalign=1.0)

image side miles angry = Image("sdf/miles_angry.webp", xalign=0.01, yalign=1.0)
image side miles growl = Image("sdf/miles_growl.webp", xalign=0.01, yalign=1.0)
image side miles bite = Image("sdf/miles_bite.webp", xalign=0.01, yalign=1.0)
image side miles bite 2 = Image("sdf/miles_bite2.webp", xalign=0.01, yalign=1.0)

image side miles angry flip = Image("sdf/miles_angry.webp", xalign=0.01, yalign=1.0)
image side miles growl flip = Image("sdf/miles_growl.webp", xalign=0.01, yalign=1.0)
image side miles bite flip = Image("sdf/miles_bite.webp", xalign=0.01, yalign=1.0)
image side miles angry gray = Image(im.Grayscale("sdf/miles_angry.webp"), xalign=0.01, yalign=1.0)
image side miles growl gray = Image(im.Grayscale("sdf/miles_growl.webp"), xalign=0.01, yalign=1.0)
image side miles bite gray = Image(im.Grayscale("sdf/miles_bite.webp"), xalign=0.01, yalign=1.0)
image side miles bite 2 gray = Image(im.Grayscale("sdf/miles_bite2.webp"), xalign=0.01, yalign=1.0)

image side miles angry flip gray = Image(im.Grayscale("sdf/miles_angry.webp"), xalign=0.01, yalign=1.0)
image side miles growl flip gray = Image(im.Grayscale("sdf/miles_growl.webp"), xalign=0.01, yalign=1.0)
image side miles bite flip gray = Image(im.Grayscale("sdf/miles_bite.webp"), xalign=0.01, yalign=1.0)

image side waiter = Image("sdfzhong_serv_b.webp", xalign=0.01, yalign=1.0)
image side waiter flip = Image("sdfzhong_serv_b.webp", xalign=0.01, yalign=1.0)
image side zhong normal = Image("sdfzhong_normal.webp", xalign=0.01, yalign=1.0)
image side zhong normal flip = Image("sdfzhong_normal.webp", xalign=0.01, yalign=1.0)
image side zhong normal b = Image("sdfzhong_normal_b.webp", xalign=0.01, yalign=1.0)
image side zhong normal b flip = Image("sdfzhong_normal_b.webp", xalign=0.01, yalign=1.0)
image side zhong normal c = Image("sdfzhong_normal_c.webp", xalign=0.01, yalign=1.0)
image side zhong normal c flip = Image("sdfzhong_normal_c.webp", xalign=0.01, yalign=1.0)
image side zhong serv = Image("sdfzhong_serv.webp", xalign=0.01, yalign=1.0)
image side zhong serv flip = Image("sdfzhong_serv.webp", xalign=0.01, yalign=1.0)
image side zhong serv b = Image("sdfzhong_serv_b.webp", xalign=0.01, yalign=1.0)
image side zhong serv b flip = Image("sdfzhong_serv_b.webp", xalign=0.01, yalign=1.0)
image side zhong serv c = Image("sdfzhong_serv_c.webp", xalign=0.01, yalign=1.0)
image side zhong serv c flip = Image("sdfzhong_serv_c.webp", xalign=0.01, yalign=1.0)
image side zhong smile = Image("sdfzhong_smile.webp", xalign=0.01, yalign=1.0)
image side zhong smile flip = Image("sdfzhong_smile.webp", xalign=0.01, yalign=1.0)
image side zhong smile b = Image("sdfzhong_smile_b.webp", xalign=0.01, yalign=1.0)
image side zhong smile b flip = Image("sdfzhong_smile_b.webp", xalign=0.01, yalign=1.0)
image side zhong smile c = Image("sdfzhong_smile_c.webp", xalign=0.01, yalign=1.0)
image side zhong smile c flip = Image("sdfzhong_smile_c.webp", xalign=0.01, yalign=1.0)

image side zhong shy b = Image("sdfzhong_shy_b.webp", xalign=0.01, yalign=1.0)
image side zhong shy b flip = Image("sdfzhong_shy_b.webp", xalign=0.01, yalign=1.0)

image side zhong shy c = Image("sdfzhong_shy_c.webp", xalign=0.01, yalign=1.0)
image side zhong shy c flip = Image("sdfzhong_shy_c.webp", xalign=0.01, yalign=1.0)

image side zhong shy = Image("sdfzhong_shy.webp", xalign=0.01, yalign=1.0)
image side zhong shy flip = Image("sdfzhong_shy.webp", xalign=0.01, yalign=1.0)



############################################Kothorix mod suport##############################################
#Declare Images
image side kothorix normal = Image( "sdf/happy_face-arms.webp", xalign=0.01, yalign=1.0)
image side kothorix normal crossed = Image("sdf/happy_face.webp", xalign=0.01, yalign=1.0)
image side kothorix normal crossed distance = Image("sdf/happy_face_side.webp", xalign=0.01, yalign=1.0)
image side kothorix displeased = Image("sdf/um_face.webp", xalign=0.01, yalign=1.0)
image side kothorix disgusted = Image("sdf/ugh_face.webp", xalign=0.01, yalign=1.0)
image side kothorix sad down = Image("sdf/sad_down.webp", xalign=0.01, yalign=1.0)
image side kothorix somber face = Image("sdf/somber_face.webp", xalign=0.01, yalign=1.0)
image side kothorix uninterested distance = Image("sdf/uninterested distance.webp", xalign=0.01, yalign=1.0)
image side kothorix hey you = Image("sdf/hey_you.webp", xalign=0.01, yalign=1.0)
image side kothorix thinking = Image("sdf/thinking.webp", xalign=0.01, yalign=1.0)
image side kothorix unamused point = Image("sdf/unamused_point.webp", xalign=0.01, yalign=1.0)
image side kothorix unamused point_distance = Image("sdf/unamused-point-side.webp", xalign=0.01, yalign=1.0) 
image side kothorix wtf = Image("sdf/wtf.webp", xalign=0.01, yalign=1.0)
image side kothorix yuno = Image("sdf/yuno.webp", xalign=0.01, yalign=1.0)
image side kothorix eyes closed = Image("sdf/eyes_closed.webp", xalign=0.01, yalign=1.0)
image side kothorix ramble = Image("sdf/ramble.webp", xalign=0.01, yalign=1.0)
image side kothorix ramble face = Image("sdf/ramble_face.webp", xalign=0.01, yalign=1.0)

#Darker images
image side kothorix normal dk = Image(im.Recolor("sdf/happy_face-arms.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix normal crossed dk = Image(im.Recolor("sdf/happy_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix normal crossed distance dk = Image(im.Recolor("sdf/happy_face_side.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix displeased dk = Image(im.Recolor("sdf/um_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix disgusted dk = Image(im.Recolor("sdf/ugh_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix sad down dk = Image(im.Recolor("sdf/sad_down.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix somber face dk = Image(im.Recolor("sdf/somber_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix uninterested distance dk = Image(im.Recolor("sdf/uninterested distance.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix hey you dk = Image(im.Recolor("sdf/hey_you.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix thinking dk = Image(im.Recolor("sdf/thinking.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix unamused point dk = Image(im.Recolor("sdf/unamused_point.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix unamused point_distance dk = Image(im.Recolor("sdf/unamused-point-side.webp" , 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix wtf dk = Image(im.Recolor("sdf/wtf.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix yuno dk = Image(im.Recolor("sdf/yuno.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix eyes closed dk = Image(im.Recolor("sdf/eyes_closed.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix ramble dk = Image(im.Recolor("sdf/ramble.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix ramble face dk = Image(im.Recolor("sdf/ramble_face.webp", 240, 240, 250, 255) , xalign=0.01, yalign=1.0)

#Flipped Images
image side kothorix normal flip = Image("sdf/happy_face-arms.webp", xalign=0.01, yalign=1.0)
image side kothorix normal crossed flip = Image("sdf/happy_face.webp", xalign=0.01, yalign=1.0)
image side kothorix normal crossed distance flip = Image("sdf/happy_face_side.webp", xalign=0.01, yalign=1.0)
image side kothorix displeased flip = Image("sdf/um_face.webp", xalign=0.01, yalign=1.0)
image side kothorix disgusted flip = Image("sdf/ugh_face.webp", xalign=0.01, yalign=1.0)
image side kothorix sad down flip = Image("sdf/sad_down.webp", xalign=0.01, yalign=1.0)
image side kothorix somber face flip = Image("sdf/somber_face.webp", xalign=0.01, yalign=1.0)
image side kothorix uninterested distance flip = Image("sdf/uninterested distance.webp", xalign=0.01, yalign=1.0)
image side kothorix hey you flip = Image("sdf/hey_you.webp", xalign=0.01, yalign=1.0)
image side kothorix thinking flip = Image("sdf/thinking.webp", xalign=0.01, yalign=1.0)
image side kothorix unamused point flip = Image("sdf/unamused_point.webp", xalign=0.01, yalign=1.0)
image side kothorix unamused point_distance flip = Image("sdf/unamused-point-side.webp", xalign=0.01, yalign=1.0)
image side kothorix wtf flip = Image("sdf/wtf.webp", xalign=0.01, yalign=1.0)
image side kothorix yuno flip = Image("sdf/yuno.webp", xalign=0.01, yalign=1.0)
image side kothorix eyes closed flip = Image("sdf/eyes_closed.webp", xalign=0.01, yalign=1.0)
image side kothorix ramble flip = Image("sdf/ramble.webp", xalign=0.01, yalign=1.0)
image side kothorix ramble face flip = Image("sdf/ramble_face.webp", xalign=0.01, yalign=1.0)

#darker flipped images
image side kothorix normal flip dk = Image(im.Recolor("sdf/happy_face-arms.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix normal crossed flip dk = Image(im.Recolor("sdf/happy_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix normal crossed distance flip dk = Image(im.Recolor("sdf/happy_face_side.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix displeased flip dk = Image(im.Recolor("sdf/um_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix disgusted flip dk = Image(im.Recolor("sdf/ugh_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix sad down flip dk = Image(im.Recolor("sdf/sad_down.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix somber face flip dk = Image(im.Recolor("sdf/somber_face.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix uninterested distance flip dk = Image(im.Recolor("sdf/uninterested distance.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix hey you flip dk = Image(im.Recolor("sdf/hey_you.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix thinking flip dk = Image(im.Recolor("sdf/thinking.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix unamused point flip dk = Image(im.Recolor("sdf/unamused_point.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix unamused point_distance flip dk = Image(im.Recolor("sdf/unamused-point-side.webp" , 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix wtf flip dk = Image(im.Recolor("sdf/wtf.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix yuno flip dk = Image(im.Recolor("sdf/yuno.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix eyes closed flip dk = Image(im.Recolor("sdf/eyes_closed.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix ramble flip dk = Image(im.Recolor("sdf/ramble.webp", 240, 240, 250, 255), xalign=0.01, yalign=1.0)
image side kothorix ramble face flip dk = Image(im.Recolor("sdf/ramble_face.webp", 240, 240, 250, 255) , xalign=0.01, yalign=1.0)


image side anna furious = Image("sdf/anna_really_mad.webp", xalign=0.01, yalign=1.0)
image side anna furious flip = Image("sdf/anna_really_mad.webp", xalign=0.01, yalign=1.0)




#update for compatability
image side miles bite b = Image("sdf/miles_bite_b.webp", xalign=0.01, yalign=1.0)
image side miles angry b = Image("sdf/miles_angry_b.webp", xalign=0.01, yalign=1.0)
image side miles growl b = Image("sdf/miles_growl_b.webp", xalign=0.01, yalign=1.0)
image side miles bite b flip = Image("sdf/miles_bite_b.webp" , xalign=0.01, yalign=1.0)
image side miles angry b flip = Image("sdf/miles_angry_b.webp" , xalign=0.01, yalign=1.0)
image side miles growl b flip = Image("sdf/miles_growl_b.webp" , xalign=0.01, yalign=1.0)

#not supported
##image side miles bite2 b = Image("sdf/miles_bite2_b.webp", xalign=0.01, yalign=1.0)
##image side miles bite2 b flip = Image( "sdf/miles_bite2_b.webp" , xalign=0.01, yalign=1.0)
##image side miles bite2 flip = Image( "sdf/miles_bite2.webp" , xalign=0.01, yalign=1.0)

image side zhong normal bx = Image("sdf/zhong_normal_bx.webp", xalign=0.01, yalign=1.0)
image side zhong normal cx = Image("sdf/zhong_normal_cx.webp", xalign=0.01, yalign=1.0)
image side zhong normal bx flip = Image("sdf/zhong_normal_bx.webp" , xalign=0.01, yalign=1.0)
image side zhong normal cx flip = Image("sdf/zhong_normal_cx.webp" , xalign=0.01, yalign=1.0)

image side reza angry dk flip = Image(im.Recolor("sdf/reza_angry.webp", 70, 70, 100, 255) , xalign=0.01, yalign=1.0)
image side reza gunpoint dk flip = Image(im.Recolor("sdf/reza_gunpoint.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side reza normal dk flip = Image(im.Recolor("sdf/reza_normal.webp", 70, 70, 100, 255) , xalign=0.01, yalign=1.0)

#not supported 
#image side reza normal2 flip = Image( "sdf/reza_normal2.webp" , xalign=0.01, yalign=1.0)
#image side reza normalx flip = Image( "sdf/reza_normalx.webp" , xalign=0.01, yalign=1.0)


image side damion arrogant flip = Image("sdf/damion_arrogant.webp" , xalign=0.01, yalign=1.0)
image side damion normal flip = Image("sdf/damion_normal.webp" , xalign=0.01, yalign=1.0)
image side damion face flip = Image("sdf/damion_face.webp" , xalign=0.01, yalign=1.0)

image side katsu normal dk flip = Image(im.Recolor("sdf/katsu_normal.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side katsu smile dk flip = Image(im.Recolor("sdf/katsu_smile.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side katsu exhausted dk flip = Image(im.Recolor("sdf/katsu_exhausted.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side katsu excited dk flip = Image(im.Recolor("sdf/katsu_excited.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)

image side maverick laugh d = Image("sdf/maverick_laugh_d.webp", xalign=0.01, yalign=1.0)
image side maverick scared c = Image("sdf/maverick_scared_c.webp", xalign=0.01, yalign=1.0)
image side maverick normal d = Image("sdf/maverick_normal_d.webp", xalign=0.01, yalign=1.0)
image side maverick scared d = Image("sdf/maverick_scared_d.webp", xalign=0.01, yalign=1.0)
image side maverick angry d = Image("sdf/maverick_angry_d.webp", xalign=0.01, yalign=1.0)
image side maverick nice d = Image("sdf/maverick_nice_d.webp", xalign=0.01, yalign=1.0)
image side maverick laugh b = Image("sdf/maverick_laugh_b.webp", xalign=0.01, yalign=1.0)
image side maverick laugh c = Image("sdf/maverick_laugh_c.webp", xalign=0.01, yalign=1.0)
image side maverick normal b flip = Image("sdf/maverick_normal_b.webp" , xalign=0.01, yalign=1.0)
image side maverick normal d flip = Image("sdf/maverick_normal_d.webp" , xalign=0.01, yalign=1.0)
image side maverick scared flip = Image("sdf/maverick_scared.webp" , xalign=0.01, yalign=1.0)
image side maverick nice d flip = Image("sdf/maverick_nice_d.webp" , xalign=0.01, yalign=1.0)
image side maverick nice b flip = Image("sdf/maverick_nice_b.webp" , xalign=0.01, yalign=1.0)
image side maverick angry dk flip = Image(im.Recolor("sdf/maverick_angry.webp", 70, 70, 100, 255) , xalign=0.01, yalign=1.0)
image side maverick angry d flip = Image("sdf/maverick_angry_d.webp" , xalign=0.01, yalign=1.0)
image side maverick angry b flip = Image("sdf/maverick_angry_b.webp" , xalign=0.01, yalign=1.0)
image side maverick scared b flip = Image("sdf/maverick_scared_b.webp" , xalign=0.01, yalign=1.0)
image side maverick scared c flip = Image("sdf/maverick_scared_c.webp" , xalign=0.01, yalign=1.0)
image side maverick laugh c flip = Image("sdf/maverick_laugh_c.webp" , xalign=0.01, yalign=1.0)
image side maverick laugh d flip = Image("sdf/maverick_laugh_d.webp" , xalign=0.01, yalign=1.0)
image side maverick laugh b flip = Image("sdf/maverick_laugh_b.webp" , xalign=0.01, yalign=1.0)
image side maverick normal dk flip = Image(im.Recolor("sdf/maverick_normal.webp", 70, 70, 100, 255) , xalign=0.01, yalign=1.0)

image side remy normal d = Image("sdf/remy_normal_d.webp", xalign=0.01, yalign=1.0)
image side remy angry d = Image("sdf/remy_angry_d.webp", xalign=0.01, yalign=1.0)
image side remy sad d = Image("sdf/remy_sad_d.webp", xalign=0.01, yalign=1.0)
image side remy look d = Image("sdf/remy_look_d.webp", xalign=0.01, yalign=1.0)
image side remy smile d = Image("sdf/remy_smile_d.webp", xalign=0.01, yalign=1.0)
image side remy shy d = Image("sdf/remy_shy_d.webp", xalign=0.01, yalign=1.0)
image side remy look dk flip = Image(im.Recolor("sdf/remy_look.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side remy normal dk flip = Image(im.Recolor("sdf/remy_normal.webp", 80, 80, 100, 255), xalign=0.01, yalign=1.0) 
image side remy smile dk flip = Image(im.Recolor("sdf/remy_smile.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side remy angry d flip = Image("sdf/remy_angry_d.webp" , xalign=0.01, yalign=1.0)
image side remy angry dk flip = Image(im.Recolor("sdf/remy_angry.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side remy shy d flip = Image("sdf/remy_shy_d.webp" , xalign=0.01, yalign=1.0)
image side remy shy dk flip = Image(im.Recolor("sdf/remy_shy.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side remy sad dk flip = Image(im.Recolor("sdf/remy_sad.webp", 80, 80, 100, 255) , xalign=0.01, yalign=1.0)
image side remy normal d flip = Image("sdf/remy_normal_d.webp" , xalign=0.01, yalign=1.0)
image side remy smile d flip = Image("sdf/remy_smile_d.webp" , xalign=0.01, yalign=1.0)
image side remy sad d flip = Image("sdf/remy_sad_d.webp" , xalign=0.01, yalign=1.0)

image side anna sad d = Image("sdf/anna_sad_d.webp", xalign=0.01, yalign=1.0)
image side anna normal d = Image("sdf/anna_normal_d.webp", xalign=0.01, yalign=1.0)
image side anna smirk d = Image("sdf/anna_smirk_d.webp", xalign=0.01, yalign=1.0)
image side anna disgust d = Image("sdf/anna_disgust_d.webp", xalign=0.01, yalign=1.0)
image side anna face d = Image("sdf/anna_face_d.webp", xalign=0.01, yalign=1.0)
image side anna rage d = Image("sdf/anna_rage_d.webp", xalign=0.01, yalign=1.0)
image side anna sad c flip = Image("sdf/anna_sad_c.webp" , xalign=0.01, yalign=1.0)
image side anna sad d flip = Image("sdf/anna_sad_d.webp" , xalign=0.01, yalign=1.0)
image side anna disgust d flip = Image("sdf/anna_disgust_d.webp" , xalign=0.01, yalign=1.0)
image side anna face c flip = Image("sdf/anna_face_c.webp" , xalign=0.01, yalign=1.0)
image side anna rage d flip = Image("sdf/anna_rage_d.webp" , xalign=0.01, yalign=1.0)
image side anna smirk d flip = Image("sdf/anna_smirk_d.webp" , xalign=0.01, yalign=1.0)
image side anna smirk c flip = Image("sdf/anna_smirk_c.webp" , xalign=0.01, yalign=1.0)
image side anna face d flip = Image("sdf/anna_face_d.webp" , xalign=0.01, yalign=1.0)
image side anna disgust c flip = Image("sdf/anna_disgust_c.webp" , xalign=0.01, yalign=1.0)
image side anna rage c flip = Image("sdf/anna_rage_c.webp" , xalign=0.01, yalign=1.0)
image side anna normal d flip = Image("sdf/anna_normal_d.webp", xalign=0.01, yalign=1.0) 
image side anna normal c flip = Image("sdf/anna_normal_c.webp" , xalign=0.01, yalign=1.0)


image side bryce sad old flip = Image("sdf/bryce_sad_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce stern old flip = Image("sdf/bryce_stern_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry old b = Image("sdf/bryce_angry_old_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce sad flip = Image("sdf/bryce_sad_flip.webp", xalign=0.01, yalign=1.0)
image side bryce brow old flip = Image("sdf/bryce_brow_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce sad b old flip = Image("sdf/bryce_sad_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry old flip = Image("sdf/bryce_angry_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce sad b old = Image("sdf/bryce_sad_b_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce angry old b flip = Image("sdf/bryce_angry_old_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce laugh old flip = Image("sdf/bryce_laugh_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce smirk old flip = Image("sdf/bryce_smirk_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce sad b flip = Image("sdf/bryce_sad_b_flip.webp", xalign=0.01, yalign=1.0)
image side bryce normal old flip = Image("sdf/bryce_normal_old_flip.webp", xalign=0.01, yalign=1.0)
image side bryce flirty old flip = Image("sdf/bryce_flirty_old_flip.webp", xalign=0.01, yalign=1.0)



image side bryce stern b dk flip = Image(im.Recolor("sdf/bryce_stern_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce normal b dk flip = Image(im.Recolor("sdf/bryce_normal_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce normal dk flip = Image(im.Recolor("sdf/bryce_normal_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce smirk b dk flip = Image(im.Recolor("sdf/bryce_smirk_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce stern dk flip = Image(im.Recolor("sdf/bryce_stern_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce brow b dk flip = Image(im.Recolor("sdf/bryce_brow_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce brow dk flip = Image(im.Recolor("sdf/bryce_brow_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce smirk dk flip = Image(im.Recolor("sdf/bryce_smirk_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce flirty b dk flip = Image(im.Recolor("sdf/bryce_flirty_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce laugh b dk flip = Image(im.Recolor("sdf/bryce_laugh_b_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce laugh dk flip = Image(im.Recolor("sdf/bryce_laugh_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)
image side bryce flirty dk flip = Image(im.Recolor("sdf/bryce_flirty_flip.webp", 70, 70, 100, 255), xalign=0.01, yalign=1.0)